### ISSUE TITLE
Consider possibility of IMultiResource interface decoupling from IERC721.

### ISSUE THREAD

**Issue by dimonkov** [rmrk-team/MultiResourceEIP#2]
Right now, IMultiResource interface has a dependency on IERC721, effectively forcing interface implementers to provide those APIs. However, it would probably be beneficial if that requirement could be lifted and that decision left to the specification adopters.  

That could allow for future token standards to implement this interface, without having to also expose IERC721 methods.

Also, since the underlying logic of the contract itself manages the flow of propose/commit for resources it could allow for cool new solutions, for example - immutable, fungible IERC1155 token with frozen array of resources, assigned on minting(since there is no single owner, no one has the permission to accept new resources. Or - some 3rd party contract has approval for resource accept by default, creating a fungible token with mutable attached resources).

As you can see, this opens the door for a lot of creative use cases for this standard, and that could potentially increase the adoption among new contracts.

**Comment by Swader** [comment]
I like this idea - this can still be made a drop-in replacement for ERC721 with additional methods, only now it is even more flexible to the point of also being a drop in replacement for ERC1155 with the right methods.

**Comment by steven2308** [comment]
Just applied the change. We're still using IERC721 on the base implementation since it's the most reasonable path, but now the interface is independent. So anyone could Implement a version of MultiResourceToken which uses IMultiResource + IERC155 or whatever else comes in the future.
Thanks for the suggestion!
